[package]
name = "count_words"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8"
crossbeam-channel = "0.5"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
floq = { path = "../../crates/core" }
